#ifndef FREQ_W_H
#define FREQ_W_H

int *freq_w(FILE *f);//RECEBE UM PONTEIRO PARA O TIPO FILE. RETORNA UM PONTEIRO PARA UM ARRAY ORDENADO USANDO COUNTSORT. RETORNA NULL EM CASO DE ERRO NA LEITURA.

#endif //FREQ_W_H
