 #ifndef READFILE_H
 #define READFILE_H

typedef struct node node;

int *freq_w(FILE *f);//RECEBE UM PONTEIRO PARA O TIPO FILE. RETORNA UM PONTEIRO PARA UM ARRAY ORDENADO USANDO COUNTSORT. RETORNA NULL EM CASO DE ERRO NA LEITURA.

 #endif